### PR TITLE
fix: update IAM policy to match the latest version for Karpenter v0.33.0

### LINKED ISSUE #150: Missing permission to create tags on spot-instances-request resources
The project is missing the `ec2:CreateTags` permission in [here](https://github.com/aws-samples/cdk-eks-karpenter/blob/v1.0.2/src/index.ts#L476-L490). Without it, deploying Karpente `v0.33.0` results in an error when trying to launch spot instances:

```json
{
    "level": "ERROR",
    "time": "2023-12-18T21:32:27.781Z",
    "logger": "controller",
    "message": "Reconciler error",
    "commit": "2dd7fdc",
    "controller": "nodeclaim.lifecycle",
    "controllerGroup": "karpenter.sh",
    "controllerKind": "NodeClaim",
    "NodeClaim": {
        "name": "nodepool-bfmb6"
    },
    "namespace": "",
    "name": "nodepool-bfmb6",
    "reconcileID": "e9ccbe9d-9393-4c8d-8734-b8bbd1bd398f",
    "error": "launching nodeclaim, creating instance, with fleet error(s), UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::AWS_ACCOUNT_ID:assumed-role/karpenterRole92C02710-LdrlCLZ4hvsL is not authorized to perform: ec2:CreateTags on resource: arn:aws:ec2:us-west-2:AWS_ACCOUNT_ID:spot-instances-request/* because no identity-based policy allows the ec2:CreateTags action."
}
```

I could solve it by manually adding the `ec2:CreateTags` in line 481.

Seems similar to https://github.com/aws/karpenter-provider-aws/issues/5270 and I don't fully get what was the solution in there, since it seems like @jls-appfire had to patch the role manually.

### PR DESCRIPTION
**Pull request by andskli**
adds permissions for AllowScopedEC2InstanceActionsWithTags and AllowScopedEC2InstanceActions for spot.

Fixes #150.

---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by andskli** [comment]
@jonathanbeber would you mind having a look? Would like another set of eyes to validate my sanity :)

**Review by jonathanbeber — COMMENTED** [review]
I will be nitpicky here, feel free to ignore me as these changes will certainly fix the issue.

I beleive that as in [the PR](https://github.com/aws/karpenter-provider-aws/commit/a946c74cbd78eac550da275362767788893eedc7#diff-d5c5758df2b080ce9df290098a5cdffe800f443c438f13213d05e327b8cadc54) that added these permissions in the docs cloudformation, we could remove line 485. To be more exact, the `spot-instances-request` resources from the statement `AllowScopedEC2InstanceActions`.

IMHO it would keep it a bit more consistent with the source.

**Comment by jonathanbeber** [comment]
thanks for working so quickly on that, @andskli. I really appreciate that.

**Comment by andskli** [comment]
@jonathanbeber no worries, appreciate the attention to detail, that resource specificatoin is not removed to match the CFN from Karpenter. Merging.

**Pull request merged**
